config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs 
  resources :users
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :styles
  resources :places, only: [:index, :show]
  resources :beer_clubs do
  resources :memberships, only: [:create, :destroy]
end
  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  #get 'kaikki_bisset', to: 'beers#index'
  #get 'ratings', to: 'ratings#index'
  #get 'ratings/new', to:'ratings#new'
  #post 'ratings', to: 'ratings#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :beer_club
  belongs_to :user
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: %i[show edit update destroy]

  # GET /memberships or /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1 or /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships or /memberships.json
  def create
    @membership = Membership.new(membership_params)
    @membership.user = current_user

    respond_to do |format|
      if @membership.save
        format.html { redirect_to beer_club_path(@membership.beer_club), notice: "#{current_user.username} welcome to the club." }
        # format.html { redirect_to membership_url(@membership), notice: "Membership was successfully created." }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1 or /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to membership_url(@membership), notice: "Membership was successfully updated." }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1 or /memberships/1.json
  def destroy
    @membership.destroy

    respond_to do |format|
      format.html { redirect_to current_user, notice: "Membership in #{@membership.beer_club.name} ended." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_membership
    @membership = Membership.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def membership_params
    params.require(:membership).permit(:beer_club_id, :user_id)
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership) do |form| %>
  <% if membership.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
        <% membership.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :beer_club_id, style: "display: block" %>
    <%= form.collection_select :beer_club_id, BeerClub.all.reject { |club| current_user.already_member_of?(club) }, :id, :name %>
  </div>

  <div>
    <%= form.submit "Create membership",  class:"btn btn-primary" %>
  </div>
<% end %>

app/views/memberships/_membership.html.erb
<div id="<%= dom_id membership %>">
  <p>
    <strong>Beer club:</strong>
    <%= membership.beer_club.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= membership.user.username %>
  </p>

</div>

app/views/memberships/edit.html.erb
<h1>Editing membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Show this membership", @membership %> |
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/index.html.erb
<h1>Memberships</h1>

<div id="memberships">
  <% @memberships.each do |membership| %>
    <%= render membership %>
    <p>
      <%= link_to "Show this membership", membership %>
    </p>
  <% end %>
</div>

<%= link_to "New membership", new_membership_path %>

app/views/memberships/new.html.erb
<h1>New membership</h1>

<%= render "form", membership: @membership %>

<br>

<div>
  <%= link_to "Back to memberships", memberships_path %>
</div>

app/views/memberships/show.html.erb
<%= render @membership %>

<div>
  <%= link_to "Edit this membership", edit_membership_path(@membership) %> |
  <%= link_to "Back to memberships", memberships_path %>

  <%= button_to "Destroy this membership", @membership, method: :delete %>
</div>