config/routes.rb
Rails.application.routes.draw do
  resources :memberships
  resources :beer_clubs 
  resources :users
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :styles
  resources :places, only: [:index, :show]
  resources :beer_clubs do
  resources :memberships, only: [:create, :destroy]
end
  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to: 'places#search'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  #get 'kaikki_bisset', to: 'beers#index'
  #get 'ratings', to: 'ratings#index'
  #get 'ratings/new', to:'ratings#new'
  #post 'ratings', to: 'ratings#create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/beer_club.rb
class BeerClub < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_admin, only: [:destroy]

  # GET /beer_clubs or /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all

    order = params[:order] || 'name'

    @beer_clubs = case order
                  when "name" then @beer_clubs.sort_by(&:name)
                  when "founded" then @beer_clubs.sort_by(&:founded)
                  when "city" then @beer_clubs.sort_by(&:city)
                  end
  end

  # GET /beer_clubs/1 or /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs or /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully created." }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1 or /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to beer_club_url(@beer_club), notice: "Beer club was successfully updated." }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1 or /beer_clubs/1.json
  def destroy
    @beer_club.destroy

    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: "Beer club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def ensure_admin
    return if current_user&.admin?

    redirect_to root_path, notice: "Only admins can perform this action."
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_beer_club
    @beer_club = BeerClub.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def beer_club_params
    params.require(:beer_club).permit(:name, :founded, :city)
  end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_beer_club.html.erb
<div id="<%= dom_id beer_club %>">
  <p>
    <strong>Name:</strong>
    <%= beer_club.name %>
  </p>

  <p>
    <strong>Founded:</strong>
    <%= beer_club.founded %>
  </p>

  <p>
    <strong>City:</strong>
    <%= beer_club.city %>
  </p>

</div>

app/views/beer_clubs/_form.html.erb
<%= form_with(model: beer_club) do |form| %>
  <% if beer_club.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
        <% beer_club.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, { :class => "form-control"} %>
  </div>

  <div>
    <%= form.label :founded, style: "display: block" %>
    <%= form.number_field :founded, { :class => "form-control"} %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city, { :class => "form-control"} %>
  </div>

  <div>
    <%= form.submit "Create Beer club", class:'btn btn-primary' %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Show this beer club", @beer_club %> |
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/index.html.erb
<h1>Beer clubs</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= link_to "Name", beer_clubs_path(order: "name") %></th>
      <th><%= link_to "Founded", beer_clubs_path(order: "founded") %></th>
      <th><%= link_to "City", beer_clubs_path(order: "city") %></th>
    </tr>
  </thead>
  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td>
          <div id="<%= dom_id beer_club %>">
            <p>
              <%= beer_club.name %>
            </p>
          </div>
        </td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
        <td>
          <%= link_to "Show this beer club", beer_club, class: "btn btn-primary" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to("New beer club", new_beer_club_path,  class:"btn btn-primary") if current_user%> 

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render "form", beer_club: @beer_club %>

<br>

<div>
  <%= link_to "Back to beer clubs", beer_clubs_path %>
</div>

app/views/beer_clubs/show.html.erb
<%= render @beer_club %>

<p>
  <strong>Members</strong>  
</p>


<div>
  <% @beer_club.users.each do |member| %>
    <p><%= link_to member.username, user_path(member.id) %></p>
  <% end %>
</div>

<% if current_user && current_user.already_member_of?(@beer_club) %>
  <%= form_with(model: current_user.memberships.find_by(beer_club_id: @beer_club.id), method: :delete) do |form| %>
    <%= form.submit "End the membership", class:"btn btn-danger" %>
  <% end %>
<% end %>

<div>
  <% if current_user %>
    <%= edit_and_destroy_buttons(@beer_club) %>
  <% end %>
</div>

<% if current_user && !current_user.already_member_of?(@beer_club) %>
  <%= form_with(model: @membership) do |form| %>
    <%= form.hidden_field :beer_club_id, value: @beer_club.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.submit "Join the beer club", class:"btn btn-primary" %>
  <% end %>
<% end %>